AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev
Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 180
    Tracing: Active